export enum Regions {
    abruzzo = "ABRUZZO",
    aosta_valley = "AOSTA VALLEY",
    apulia = "APULIA",
    basilicata = "BASILICATA",
    calabria = "CALABRIA",
    campania = "CAMPANIA",
    emilia_romagna = "EMILIA-ROMAGNA",
    friuli_venezia_giulia = "FRIULI-VENEZIA GIULIA",
    lazio = "LAZIO",
    liguria = "LIGURIA",
    lombardy = "LOMBARDY",
    marche = "MARCHE",
    molise = "MOLISE",
    piedmont = "PIEDMONT",
    sardinia = "SARDINIA",
    sicily = "SICILY",
    trentino_south_tyrol = "TRENTINO-SOUTH TYROL",
    tuscany = "TUSCANY",
    umbria = "UMBRIA",
    veneto = "VENETO",
}